[package]
name = "ls"
version = "0.3.0"
authors = ["The Noah <thenoahbz@gmail.com>"]
edition = "2018"
description = "The best ls command (I hope)"
readme = "README.md"
homepage = "https://github.com/The-Noah/ls"
repository = "https://github.com/The-Noah/ls"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
